# Numpy


In [2]:
import numpy as np
import time

In [19]:
# Decorator to note down the time

import time

def time_it(func):
    def wrapper(*args, **kwargs):
        start_t = time.time()
        result = func(*args, **kwargs)
        end_t = time.time()
        time_taken = end_t - start_t
        print(f"Time Taken : {time_taken}")
        return time_taken   # return timing
    return wrapper


@time_it
def python_add():
    a = list(range(1_000_000))
    b = list(range(1_000_000))
    c = [x + y for x, y in zip(a, b)]
    return c   # optional but good practice


time_taken = python_add()
print("Returned time:", time_taken)


Time Taken : 0.13935303688049316
Returned time: 0.13935303688049316


In [25]:
a = list(range(1000000))
b = list(range(1000000))

start_t = time.time()
c = [x + y for x,y in zip(a,b)]
end_t = time.time()
time_taken_p = end_t - start_t
print(f"Time Taken: {time_taken_p}")


Time Taken: 0.08243703842163086


In [27]:
time_taken_p/time_taken

0.5915697301403449

# Numpy Array
### np.array()

In [29]:
# In arrays we cant store multiple data types they hold same data in form of list 
# It is of dimension ndarray
# 1. np.array()

array_n1 = np.array([1,2,3,4])

In [31]:
print(array_n1)
print(type(array_n1))
print(type(array_n1[0]))

[1 2 3 4]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [33]:
array_n1 = np.array([1,2,3], dtype = np.int8)
print(type(array_n1))
print(type(array_n1[0]))

<class 'numpy.ndarray'>
<class 'numpy.int8'>


In [36]:
array_n2 = np.array([1,2,"3"], dtype = np.int8)
print(array_n2)
print(type(array_n2))
print(type(array_n2[0]))


[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.int8'>


In [37]:
array_n3 = np.array([1,2,"3"], dtype = np.float16)
print(array_n3)
print(type(array_n3))
print(type(array_n3[0]))


[1. 2. 3.]
<class 'numpy.ndarray'>
<class 'numpy.float16'>


# 2. np.arange(start,stop,step)

In [41]:
print(np.arange(5))

print(np.arange(1,10, 2))

np_arange = np.arange(1,10,2)
print(type(np_arange))



[0 1 2 3 4]
[1 3 5 7 9]
<class 'numpy.ndarray'>


# 3. np.linspace(start, stop, num =x)
#### To get evenly spaced numbers between numbers 

In [43]:
np_linspace = np.linspace(0,1,10)
print(np_linspace)
print(type(np_linspace))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
<class 'numpy.ndarray'>


In [44]:
for i in np.linspace(1,10,10):
    print(i)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


# np.zeros(shape)

In [ ]:
npz_1 = np.zeros(5)

In [ ]:
npz_1.ndim # ndim is for getting dimension 

1

In [50]:
a = [ [1,2,3], [2,4,5]]  # This is 2D list

In [51]:
a[1]

[2, 4, 5]

In [ ]:
b = a = [ [1,2,3], [2,4,5]], [[1,2,3], [2,4,5]]    # This is 3d

In [53]:
b[1]


[[1, 2, 3], [2, 4, 5]]

In [56]:
npz_3 = np.zeros((5,5,5))
print(npz_3)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [58]:
npz_3.ndim

3

In [59]:
### np.zeros()

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [60]:
# Dimension of array

np.zeros((5,5)).shape

(5, 5)

In [62]:
np.zeros((5,5)).ndim

2

# np.ones

In [63]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# np.full()

In [64]:
# list of size 10, all filled with valus of 5

In [65]:
np.full((5,5), 0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [66]:
np.full((5,5), 100)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [67]:
np.full(10,5)
# np.full(shape, fill_values)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

# np.eye(n)
### Used for getting identity matrix

In [68]:
np.eye(6,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

# np.empty(shape)
### This is to get dummy values

In [69]:
a = np.full((5,5), 0)     #  a is a numpy array with size 5,5 with all zeros

In [70]:
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [71]:
np.empty((5,5))

array([[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
        -1.27129110e-310,  1.14416809e-071],
       [ 9.41671318e-067,  9.96449615e-047,  1.47819241e-075,
         2.76762381e-057,  5.18815293e-144],
       [ 3.59751658e+252,  3.96046095e+246,  1.04918621e-153,
         7.69165785e+218,  5.04621343e+180],
       [ 1.04917822e-153,  9.08366793e+223,  1.14416809e-071,
         9.41671318e-067,  9.96449615e-047],
       [ 1.47819241e-075,  1.04917877e-153,  1.94918966e-153,
         9.15563579e-072,  9.72680298e-067]])

In [ ]:
np.empty((5,5),dtype = int)   # To get dummy values , the numbers below are garbage values 

array([[1420976169552, 1420976170944, 1420976161872, 1420976172240,
        1420976176848],
       [1420976168208, 1420976168448, 1420976170080, 1420976174064,
        1420976167680],
       [1421344247600, 1421048879872, 1421048879104, 1421048876464,
        1421048877952],
       [1421048874352, 1421048874496, 1421344247664, 1421048878240,
        1421048879152],
       [            0,             0,             0,             0,
                    0]])

# np.random.rand(shape)
### Generates random numbers between 0 and 1 from a uniform distribution 

In [79]:
np.random.rand(5,5)

array([[0.63433768, 0.90417168, 0.08006245, 0.57480815, 0.4325145 ],
       [0.93597792, 0.87347196, 0.2466488 , 0.2946263 , 0.80943693],
       [0.23577888, 0.55227273, 0.82832768, 0.2766943 , 0.28479215],
       [0.21851731, 0.25979991, 0.43328758, 0.01369154, 0.81891814],
       [0.18776057, 0.78626169, 0.9400586 , 0.60502668, 0.61547393]])

In [80]:
a = np.random.rand(10)*100

a = a.tolist()

a

[32.885182718312024,
 53.088475258778786,
 85.81095104660662,
 10.327500686434366,
 81.21928181896595,
 33.76259281168985,
 40.086355122413465,
 93.60610430953898,
 39.97432678666969,
 7.560035796573706]

In [81]:
a = [int(i) for i in a]

In [82]:
print(a)

[32, 53, 85, 10, 81, 33, 40, 93, 39, 7]


In [83]:
np.random.randint(1, 10, 10)

array([9, 3, 4, 7, 1, 7, 9, 5, 8, 1], dtype=int32)

# Assignment 
#### 1D aaray of numbers from 0 to 9
#### A 3 x 3 matrix of all 5s
#### A 4 x 4 identity matrix 
#### 10 evenly spaced numbers between 1 to 100
#### A 2 x 2 array with random values between 0 and 1 

In [3]:
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
matrix = np.full((3,3), 5)
print(matrix)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [7]:
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
arr4 = np.linspace(1, 100, 10)
print(arr4)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [9]:
arr5 = np.random.rand(2,2)
print(arr5)

[[0.29250165 0.75160972]
 [0.63300966 0.1225553 ]]


# Numpy attributes

In [10]:
arr = np.array([[1,2,3], [4,5,6]])

In [11]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [12]:
arr.shape

(2, 3)

In [14]:
arr.ndim

2

In [15]:
arr.dtype

dtype('int64')

# ndarray.itemsize

In [ ]:
arr.itemsize   # bytes  <-- size of each element in bytes

8

In [17]:
# 1 gb --> 1024 mb
# 1 mb --> 1024 kb
# 1 kb --> 1024 bytes
# 1 byte --> 8 bit

In [20]:
arr.nbytes # Total number of bytes consumed by the arr --> Total memoty usage (size x itemsize)

48

In [21]:
# Transpose of the array

arr

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [23]:
a = np.array([1,2,3])

In [24]:
print(a)
print(a.T)

[1 2 3]
[1 2 3]


In [25]:
print(a.shape)
print(a.T.shape)

(3,)
(3,)


In [26]:
print(a)


[1 2 3]


In [29]:
z = np.full((3,5), 3)
print(z)
z = z.T
print(z)

[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]
[[3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]]


# Indexing and slicing 

In [42]:
arr = np.array([10,20,30,40,50,60])

In [43]:
print(arr[0])
print(arr[-1])

10
60


In [44]:
print(arr[-1])

60


In [47]:
print(arr[1:4])
print(arr[:3])

[20 30 40]
[10 20 30]


In [49]:
print(arr[::2])     # (start with 0 and step size of 2)

[10 30 50]


In [50]:
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [53]:
print(mat[0,1])
print(mat[1])
print(mat[:,2])
print(mat[:,-1])

2
[4 5 6]
[3 6 9]
[3 6 9]


In [54]:
print(mat[0:2,1:])

[[2 3]
 [5 6]]


In [55]:
arr_temp = np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
arr_temp[::-1]      # Reverse order

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [60]:
print(mat[::-1, ::-1])

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [61]:
arr = np.array([5,10,15,20,25])

In [62]:
arr > 10

array([False, False,  True,  True,  True])

In [64]:
print(arr[arr > 10])   # Boolean indexing 

[15 20 25]


In [65]:
indx = [0,3,4]
arr[indx]

array([ 5, 20, 25])

In [66]:
arr[0] = 50
print(arr)

[50 10 15 20 25]


# Indexing with np.where()

In [73]:
arr8 = np.array([5,10,15,20,25,30])

In [74]:
idx = np.where(arr8 >20)
print(idx)

(array([4, 5]),)


In [75]:
print(arr[idx])

[25 30]


# Array reshaping and resizing 

In [76]:
arr = np.array([1,2,3,4,5,6])

In [77]:
arr.shape

(6,)

In [81]:
reshaped = arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [ ]:
# When the array of list is too large it will throw error if vaues are insufficient 

arr = np.array([1,2,3,4,5,6,7,8,9,0,12,2,3,4,5])
reshaped = arr.reshape(3,-1)
print(reshaped)

[[ 1  2  3  4  5]
 [ 6  7  8  9  0]
 [12  2  3  4  5]]


In [87]:
reshaped.shape

(3, 5)

In [89]:
a = np.array([[1,2], [3,4]])

In [90]:
b = a.flatten()

In [91]:
b

array([1, 2, 3, 4])

In [92]:
a= np.array([1,2,3,4])

In [93]:
a.resize((2,3))

In [94]:
print(a)

[[1 2 3]
 [4 0 0]]


In [97]:
a.resize((3,3)) # Resize will truncate or padd with zeros 

In [98]:
print(a)

[[1 2 3]
 [4 0 0]
 [0 0 0]]


In [99]:
a = np.array([[[1],[2],[3]]])
print(a.shape)

(1, 3, 1)


In [100]:
b = np.squeeze(a)
print(b)

[1 2 3]


In [101]:
print(b.shape)

(3,)


# Numpy Math Operations

In [103]:
# This is appending 

a = [1,2,3]
b = [4,5,6]

a + b

[1, 2, 3, 4, 5, 6]

In [104]:
# How to add with numpy

a = np.array([1,2,3])
b = np.array([4,5,6])


In [105]:
a + b 

array([5, 7, 9])

In [108]:
print(a - b)
print( a * b)
print( a/b )

[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [111]:
# Comparison operator 
print( a > b)
print( a < b)
print( a == b)

[False False False]
[ True  True  True]
[False False False]


In [113]:
ans = a > b
print(type(ans[0]))

<class 'numpy.bool'>


In [115]:
# Logical Operators 
# and , or , not 

x = np.array([True, False, True])
y = np.array([False, False, True])

print(np.logical_and(x,y))
print(np.logical_or(x,y))
print(np.logical_not(x))

[False False  True]
[ True False  True]
[False  True False]


# Bitwise Operators 

In [117]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.bitwise_and(a,b))
print(np.bitwise_or(a,b))

[0 0 2]
[5 7 7]


In [123]:
# Modulus and Power    % remainder 
a = np.array([10,20,30])
b = np.array([3,7,4])

print(np.mod(a,b))
print(np.power(a,b))
print(np.remainder(a,b))


[1 6 2]
[      1000 1280000000     810000]
[1 6 2]


# Scalar Operations 

In [126]:
celcius = np.array([0, 10, 20, 30])

to_farenheit = (9/5 + 32)
print(to_farenheit)

33.8


In [128]:
# to_farenheit = np.array([33.8, 33.8, 33.8, 33.8]) # Broadcasting
print(celcius * to_farenheit)       # Broadcasting 

[   0.  338.  676. 1014.]


In [130]:
# In python   -- Not possible 
celcius = [0, 10, 20, 30]
farenheit = celcius * 9 / 5 + 32
print(farenheit)

TypeError: unsupported operand type(s) for /: 'list' and 'int'

# Common maths Functions 

In [ ]:
a = np.array([1,2,3,4])

print(np.sqrt(a))
print(np.exp(a))   # e ^ 1, e^ 2  where = 2.718
print(np.log(a))
print(np.sin(a))

[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [135]:
# In Machine Learning 
# ACtivation function 

# sigmoid  = 1/ 1 + e^-x

x = np.array([-1, 0, 1])

sigmoid = 1 / (1 + np.exp(~x))
print(sigmoid)

[0.5        0.73105858 0.88079708]


In [136]:
# Aggregation Functions 

In [137]:
a = np.array([[1,2,3],
              [4,5,6]])

In [139]:
print(np.sum(a))     # Sum of 1 + 2 + 3 + 4 + 5 + 6

21


In [141]:
print(np.sum(a, axis = 0 ))   # across all rows fix the column

[5 7 9]


In [142]:
print(np.mean(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))

3.5
1.707825127659933
1
6


# Matrix Operation

In [149]:
# Element wise multiplication
# We can use it when the arrays are of same shape, also if you need to multiply each element individually

units = np.array([100, 200, 150])
profit = np.array([10, 20, 30])

In [150]:
units * profit

array([1000, 4000, 4500])

# Matrix Multiplication or Dot product
#### Rule 1 - Columns of the first matrix must be equal to rows of second matrix

##### if yes:
    ####    result shape = rows of first matrix, column of second 
             ####        = (2,2)

# Dot Product - It does multiplication of all elements and the sums them as well across colums, So it does two steps

In [175]:
# sqft
# bedroom
# Location 1 is good and 0 is bad

house = np.array([1200, 3, 1])



In [176]:
w = np.array([200, 10000, 50000])

In [177]:
print(house.shape)
print(w.shape)

(3,)
(3,)


In [168]:
np.dot(house,w)   # 1200 * 200 + 3 * 10000 + 1 * 50000 = 3200000

np.int64(320000)

In [179]:
house = np.array([[1200, 3, 1],
                  [1200, 3, 0],
                  [1000, 3, 0],
                  [1000, 1, 1]])

In [180]:
w = np.array([200, 10000, 50000])

In [181]:
print(np.dot(house,w))

[320000 270000 230000 260000]


In [182]:
print(np.sum(house * w, axis = 1))  # multiplication + sum

[320000 270000 230000 260000]


In [183]:
A = np.array([[1,2,3,4],[1,2,3,4]])
B = np.array([[1,2,3,4],[1,2,3,4]])

In [185]:
print(A.shape)
print(B.shape)

(2, 4)
(2, 4)


In [193]:
print(np.dot(A,B.T))           



[[30 30]
 [30 30]]


In [192]:
print(A @ B.T)


[[30 30]
 [30 30]]


# BroadCasting 
### WE can use these when we have two different shapes 

In [195]:
a = np.array([1, 2, 3])    # (3,)
b = np.array([[10], [20]])  # (2,1)

In [196]:
print(a.shape)
print(b.shape)

(3,)
(2, 1)


In [199]:
a + b 

# BELOW This is what numpy will do 
# a --> (2,3) [[1,2,3], [1,2,3]]
# b --> [[10,10,10], [20,20,20]]                

array([[11, 12, 13],
       [21, 22, 23]])

# Creating Arrays from existing data

In [202]:
a = [1,2,3,4]
b = ([[1,2], [2,3]])
c = (10, 20, 30)

In [207]:
a_npy = np.array(a)
print(a_npy, a_npy.dtype, a_npy.dtype, type(a))

[1 2 3 4] int64 int64 <class 'list'>


In [208]:
b_npy = np.array(b)
print(b_npy, b_npy.dtype, b_npy.dtype, type(b))

[[1 2]
 [2 3]] int64 int64 <class 'list'>


In [209]:
c_npy = np.array(c)
print(c_npy, c_npy.dtype, c_npy.dtype, type(c))

[10 20 30] int64 int64 <class 'tuple'>


In [210]:
# Vstack

a = np.array([[1,2]])
b = np.array([[3,4]])

In [211]:
print(np.vstack((a,b)))

[[1 2]
 [3 4]]


In [212]:
print(np.hstack((a,b)))

[[1 2 3 4]]


In [213]:
# Working with String Characters 
# np.char <function_name>()
# 1. np.add()

a = np.array(["Hello", "world"])
b = np.array(["_user", "_123"])

print(np.char.add(a,b))

['Hello_user' 'world_123']


In [214]:
# np.char.multiply()

print(np.char.multiply(a,2))

['HelloHello' 'worldworld']


In [215]:
# np.char.upper() / Lower() / capitalize()

a = np.array(['hello', 'WORLD'])

print(np.char.upper(a))
print(np.char.lower(a))
print(np.char.capitalize(a))

['HELLO' 'WORLD']
['hello' 'world']
['Hello' 'World']


In [217]:
# np.char.center()
# This is called as padding 
print(np.char.center(a, 10, fillchar = '*'))

['**hello***' '**WORLD***']


In [218]:
a = np.array(['data_science', 'machine_learning'])

In [219]:
# np.char.replace()

print(np.char.replace(a, '_', ' '))

['data science' 'machine learning']


In [221]:
# np.char.split()

print(np.char.split(a, sep = '_'))

[list(['data', 'science']) list(['machine', 'learning'])]


In [222]:
# np.char.find() / np.char.count()

print(np.char.find(a, 'learn'))
print(np.char.count(a, 'a'))
print(np.char.count(a, 'data'))

[-1  8]
[2 2]
[1 0]


# Statistical functions

In [223]:
data = np.array([1,2,3,4,5,6,7])

In [226]:
print("Mean:", np.mean(data))
print("Median", np.median(data))
print("Standard Deviation:", np.std(data))
print("Variance:", np.var(data))
print("Min:", np.min(data))
print("Max:", np.max(data))

Mean: 4.0
Median 4.0
Standard Deviation: 2.0
Variance: 4.0
Min: 1
Max: 7


In [230]:
# Argmax is max of value
# Argmin is min of value

print("Argmic:", np.argmin(data))
print("Argmax:", np.argmax(data))

Argmic: 0
Argmax: 6


In [231]:
# Index of min and max values 

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])


print(np.mean(matrix,axis = 0))
print(np.mean(matrix, axis = 1))

[2.5 3.5 4.5]
[2. 5.]


In [233]:
# Percentile ---> Indicates the values below certain percenatge of obervation 

data = np.array([1, 3, 5, 7, 9])
print(np.percentile(data, 50))
print(np.quantile(data, 0.75))

5.0
7.0


In [234]:
print(np.quantile(data, 0.9))

8.2


# Sort, Search and Counting Functions 

In [240]:
arr = np.array([3,1,4,5,1,8,4,1,2,9,1])

print("Sorted:", np.sort(arr))
print("Sorted indices:", np.argsort(arr))
print("Insert 4 position:", np.searchsorted(np.sort(arr), 4))
print("Unique elements:", np.unique(arr))
print("Count of each element:", np.bincount(arr))


# min - 1
# max - 8 
# Creates an array from 0 to max element(8)
# 0, 1, 2, 3, 4, 5, 6, 7, 8 ---> len(9)

Sorted: [1 1 1 1 2 3 4 4 5 8 9]
Sorted indices: [ 1  4  7 10  8  0  6  2  3  5  9]
Insert 4 position: 6
Unique elements: [1 2 3 4 5 8 9]
Count of each element: [0 4 1 1 2 1 0 0 1 1]


In [242]:
arr = np.array([1, 2, 3, 4])

for x in arr:
    print(x)

1
2
3
4


In [244]:
arr_2d = np.array([[1, 2], [3, 4]])

In [245]:
for x in arr_2d:
    print(x)

[1 2]
[3 4]


In [246]:
arr = np.arange(8).reshape(2,2,2)
print(arr)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [247]:
arr = np.arange(8).reshape(2,2,2)

for x in np.nditer(arr):
    print(x)

0
1
2
3
4
5
6
7


In [248]:
a = np.array([1,2, 3])

In [249]:
b = a

In [250]:
b[0] = 100


In [251]:
print(a)

[100   2   3]


In [257]:
a = np.array([1, 2, 3])

In [261]:
b = a 

In [262]:
b = a.copy()

In [263]:
b[0] = 100

In [265]:
print(a)


[1 2 3]


In [3]:
a = np.array([1,2,3])

b = a.view()

c = a.copy()

In [4]:
b[0] = 10
print(a)

[10  2  3]


In [5]:
c[0] = 20
print(a)

[10  2  3]


In [6]:
a = np.arange(5)
b = a[1:4]

print(np.shares_memory(a,b))

True


In [7]:
a = np.arange(5)
b = a[1:4].copy()

print(np.shares_memory(a,b))

False
